server:
  port: 2222

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail: #arceniy.devyatkin@yandex.ru
    host: smtp.yandex.ru
    port: 587
    username: arceniy.devyatkin@yandex.ru
    password: jhjhvvpzatcgedpx
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

